export const GAME_PHASES = {
  UNIT_PLACEMENT: 'UNIT_PLACEMENT',
  START_GAME: 'START_GAME',
  TURN_START: 'TURN_START',
  ACTION_SELECTION: 'ACTION_SELECTION',
  MOVEMENT: 'MOVEMENT',
  ATTACK: 'ATTACK',
  DEFENSE: 'DEFENSE',
  EFFECT: 'EFFECT',
  TURN_END: 'TURN_END',
};
